### ISSUE TITLE
Only macOS has 1.9, everything else is on 1.6

### ISSUE THREAD

**Issue by itamarst** [conda-forge/crochet-feedstock#6]
Looking at  https://anaconda.org/conda-forge/crochet, it looks like only macOS has 1.9, everything else is still at 1.6. Not sure why.

I just released 1.10 so maybe that will build.

Also if you want you can add me as maintainer, I already maintain a couple of conda-forge feedstocks.

**Comment by stuertz** [comment]
Hm, that's bad. I will have to look into that.
Just merged the 1.10 changes from autotick. Maybe that will fix it. (But I have not much hope into this :-) )  

Thanks for your support, I will add you as maintainer in the next hours.

**Comment by itamarst** [comment]
Thank you, and thank you for maintaining the conda-forge package!

**Comment by itamarst** [comment]
Looks like it build a 1.10 noarch, so maybe it's fine now?

**Comment by stuertz** [comment]
Yes it should be.
